"""Simulated scenarios.

Each one is built to isolate a single failure mode, because a scenario where
everything is hard at once tells you a tracker is worse without telling you
which part is worse.

  crossing    - two targets that meet. Tests association identity, nothing else.
  manoeuvre   - one target, one hard turn, no clutter. Tests the filter bank.
  dense       - many targets in heavy clutter. Tests the whole thing at load.

Truth is generated by propagating the *same* motion models the filter uses,
which is a deliberate choice and a limitation: it means these numbers measure
estimation and association quality, not model mismatch. A real trial has to be
flown against recorded data, and the ADS-B loader in `adsb.py` is there for it.
"""

import numpy as np

from .models import ct, cv


class Scenario:
    def __init__(self, name, truth, scans, meta=None):
        self.name = name
        self.truth = truth      # list of {target_id: (x, y)} per scan
        self.scans = scans      # list of (m, 2) measurement arrays
        self.meta = meta or {}

    def __len__(self):
        return len(self.scans)


def _propagate(x, legs, dt):
    """Run a state through a list of (n_steps, turn_rate_deg) legs."""
    out = []
    for steps, rate in legs:
        F = cv(dt) if rate == 0.0 else ct(np.deg2rad(rate), dt)
        for _ in range(steps):
            x = F @ x
            out.append(x.copy())
    return out


def _measure(paths, sigma, Pd, clutter, bounds, rng):
    """Turn truth into scans: detections thinned by Pd, plus Poisson clutter."""
    n_scans = len(next(iter(paths.values())))
    truth, scans = [], []
    (xlo, xhi), (ylo, yhi) = bounds

    for k in range(n_scans):
        frame = {}
        pts = []
        for tid, path in paths.items():
            pos = np.array([path[k][0], path[k][2]])
            frame[tid] = pos
            if rng.random() < Pd:
                pts.append(pos + rng.normal(0.0, sigma, 2))

        n_false = rng.poisson(clutter)
        for _ in range(n_false):
            pts.append(np.array([rng.uniform(xlo, xhi), rng.uniform(ylo, yhi)]))

        rng.shuffle(pts)
        truth.append(frame)
        scans.append(np.asarray(pts).reshape(-1, 2))

    return truth, scans


def crossing(n_scans=40, dt=1.0, sigma=20.0, Pd=0.95, clutter=2.0, seed=0):
    """Two targets on converging straight legs that cross mid-run.

    The canonical association test. Near the crossing both measurements sit in
    both gates, and a hard assignment has no information to break the tie with.
    """
    rng = np.random.default_rng(seed)
    span = n_scans * dt
    speed = 100.0
    a = np.array([-speed * span / 2, speed, -1500.0, 3000.0 / span])
    b = np.array([speed * span / 2, -speed, -1500.0, 3000.0 / span])
    paths = {0: _propagate(a, [(n_scans, 0.0)], dt),
             1: _propagate(b, [(n_scans, 0.0)], dt)}
    bounds = ((-4000, 4000), (-3000, 3000))
    truth, scans = _measure(paths, sigma, Pd, clutter, bounds, rng)
    return Scenario("crossing", truth, scans,
                    {"targets": 2, "clutter": clutter, "Pd": Pd})


def manoeuvre(n_scans=60, dt=1.0, sigma=20.0, Pd=0.98, clutter=0.5, seed=0,
              turn_rate=6.0):
    """One target: straight, hard turn, straight.

    No association difficulty on purpose — whatever the tracker loses here it
    lost in the filter, not in the assignment.
    """
    rng = np.random.default_rng(seed)
    x0 = np.array([-3000.0, 120.0, 0.0, 0.0])
    third = n_scans // 3
    legs = [(third, 0.0), (third, turn_rate), (n_scans - 2 * third, 0.0)]
    paths = {0: _propagate(x0, legs, dt)}
    bounds = ((-4000, 4000), (-1000, 4000))
    truth, scans = _measure(paths, sigma, Pd, clutter, bounds, rng)
    return Scenario("manoeuvre", truth, scans,
                    {"targets": 1, "turn_rate": turn_rate, "Pd": Pd})


def dense(n_scans=50, n_targets=6, dt=1.0, sigma=20.0, Pd=0.9, clutter=10.0,
          seed=0):
    """Several manoeuvring targets in heavy clutter, in a shared volume.

    This is the one that makes JPDA's cost visible: targets are close enough
    that gates overlap, so clusters stop being singletons.
    """
    rng = np.random.default_rng(seed)
    paths = {}
    for i in range(n_targets):
        angle = 2.0 * np.pi * i / n_targets
        r = 2500.0
        speed = 90.0
        x0 = np.array([r * np.cos(angle), -speed * np.cos(angle),
                       r * np.sin(angle), -speed * np.sin(angle)])
        rate = 0.0 if i % 2 == 0 else (5.0 if i % 4 == 1 else -5.0)
        legs = [(n_scans // 2, 0.0), (n_scans - n_scans // 2, rate)]
        paths[i] = _propagate(x0, legs, dt)

    bounds = ((-3000, 3000), (-3000, 3000))
    truth, scans = _measure(paths, sigma, Pd, clutter, bounds, rng)
    return Scenario("dense", truth, scans,
                    {"targets": n_targets, "clutter": clutter, "Pd": Pd})
